# Generated by Django 3.2.19 on 2024-06-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Impact', '0002_auto_20240617_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='faculte',
            new_name='isFaculte',
        ),
    ]
