# Generated by Django 3.2.19 on 2024-06-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impact', '0003_rename_faculte_faculty_isfaculte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='isFaculte',
            field=models.IntegerField(default=1),
        ),
    ]
