# Generated by Django 3.2.19 on 2024-06-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impact', '0004_alter_faculty_isfaculte'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='credit',
            field=models.IntegerField(default=1),
        ),
    ]
