# Generated by Django 5.0.6 on 2024-07-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impact', '0007_ue_sigle'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
