# Generated by Django 5.0.6 on 2024-07-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Impact', '0008_filiere_delete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('name', 'faculty', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='ue',
            unique_together={('name', 'filiere', 'year', 'semester')},
        ),
    ]
