# Generated by Django 5.0.6 on 2024-07-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impact', '0009_alter_filiere_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
