# Generated by Django 5.0.6 on 2024-07-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impact', '0010_ue_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_year',
        ),
        migrations.AddField(
            model_name='studentyear',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
