# Generated by Django 5.0.6 on 2024-07-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impact', '0011_remove_student_current_year_studentyear_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentyear',
            name='enjambed',
            field=models.BooleanField(default=False),
        ),
    ]
