# Generated by Django 5.0.6 on 2024-07-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impact', '0012_studentyear_enjambed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentyear',
            name='compo',
            field=models.BooleanField(default=False),
        ),
    ]
